In [8]:
import pandas as pd

from datetime import datetime

# Load the csv files
table = pd.read_csv('car_prices.csv')

# Convert the 'saledate' column to datetime type (first remove the timezone part)
table['saledate'] = table['saledate'].astype(str).str.replace(' (PST)', '')
table['saledate'] = table['saledate'].astype(str).str.replace(' (PDT)', '')

def parse_date(date_str):
    try:
        return datetime.strptime(date_str, '%a %b %d %Y %H:%M:%S %Z%z').strftime('%m/%d/%Y')
    except ValueError:
        return None  # or you can handle it as a different value

# Find null item
null_rows = table[table.isnull().any(axis=1)]

# Drop the rows with null values
table = table.dropna()

# Convert saledate column to datetime type and apply parse_date function
table['saledate'] = table['saledate'].apply(parse_date)
table['saledate'] = pd.to_datetime(table['saledate'], errors='coerce')


#Check if there is still any null items in the dataframe
check_for_nulls = table.isnull().values.any()

#Print the updated table
table

# Export to csv file for the output 
filename = 'output.csv'
table.to_csv(filename, index=False)
print(f"The table is saved as '{filename}'.")

The table is saved as 'output.csv'.

object

C:\Users\Zack\AppData\Local\Temp\ipykernel_10964\2089001402.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table_no_nulls['saledate'] = table['saledate'].apply(parse_date)

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,12/16/2014
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,12/16/2014
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,01/15/2015
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,01/29/2015
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,12/18/2014